version: "3.2"
services:
  app-env-runtime:
    image: app-env-runtime
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "5000:5000"
    environment:
      - API_URL= http://dijalma.com.br