version: "3.2"
services:
  app:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://url-docker-compose.com.br
      - API_NAME=Name from docker-compose